#+TITLE:rewritestrcsp
#+STARTUP: showall indent align inlineimages nologdone
#+FILETAGS:
#+TAGS: 

* Introduction
** Using structured cospans to introduce inductive rewriting on certain topoi
** generalizing gadducci.
* Structured Cospans
** Introduce the section 
*** Background on structured cospans
**** decorated cospans
**** structured cospans
*** introduce some notation here
**** spans are x --> y \times z and cospans too
*** minimum assumptions at this point: working with a geom. morphism
** Structured cospans as objects 
*** define the category StrCsp(L) of structured cospans as objects
*** analogy to open systems and the role each part of the geom. morphism plays  
*** start running example: open/ranked graphs
**** mention gaducci and kissinger stuff here
*** prove that StrCsp : [ * --> * , Topos ] --> Topos is functor
**** requires proving that StrCsp(L) is a topos using Artin gluing
*** the category of structured cospan categories is a functor category so the functors should be certain natural transformations. Does the current definition of a structured cospan functor do this?
** Structured cospans as arrows
*** this intros compositionality to structured cospans
*** define the composition of structured cospans via pushout
*** illustrate with open graphs
** A double category of structured cospans
*** hand wavey definition of double category. Point to shulman for definition
*** This is the most natural structure to capture structured cospans. Bicategories are an alternative, but having the vertical arrows there is nice.
*** Define double category SStrCsp:=[ob(A), A-arrows, StrCsps, StrCsp-arrows]
* Inductive Rewriting of Structured Cospans
** Introduce the section
*** extra conditions on geom. morphism: 
**** counit is monic
**** in suboject algebra, (k=>LRk) U k = d
** Graph rewriting
*** production of graphs
*** graph grammars
*** injective matching only
*** pushout complement
*** rewrite relation
*** discrete rewrite relation = rewrite relation
*** Gaducci's contrution and result
** Adhesive rewriting
*** adhesive categories
**** Van Kampen condition
*** productions
*** adhesive grammars
**** category Gram
*** injective matching
*** pushout complement
*** Derivations is functorial Gram --> Gram
**** idempotent
**** identity on Gram is subfunctor of derivation
*** Rewrite relation in terms of derivation functor
*** The language functor and its relation to the rewrite relation
** Rewriting structured cospans
*** StrCsp(L) < topoi < adhesive to can do rewriting
*** Define the subcategory of Gram of Structured Cospans Grammars StrGram.
*** Define Structured Cospan Language functor StrGram --> DblCat
**** Uses the double category MonRewrite in which to generate sub-double cats. 
*** thm: production and discrete production have same rewrite relation
*** thm: rewrite relation same as squares from 0 to 0.
** Examples
*** Encoding petri nets into dpo rewrites (see bib folder for Graph Rewriting w Petri Nets)
* Bibliography
** D.\ Cicala. Spans of cospans. \emph{Theory Appl.\ Categ.\} 33, Paper No.\ 6, 131--147. 2018.
** D.\ Cicala and K.\ Courser. Spans of cospans in a topos. \emph{Theory Appl.\ Categ.} 33, Paper No.\ 1, 1--22. 2018.
** L.\ Dixon, and A.\ Kissinger. Open-graphs and monoidal theories. \emph{Math.\ Structures Comput.\ Sci.\}, \textbf{23}, no.\ 2, 308--359. 2013.
** H.\ Ehrig, M.\ Pfender, and H.J.\ Schneider. Graph-grammars: An algebraic approach. In \emph{Switching and Automata Theory, 1973. SWAT'08. IEEE Conference Record of 14th Annual Symposium on}, 167--180. IEEE. 1973.
** B.\ Fong. Decorated cospans. \emph{Theory Appl.\ Categ.\} 30, Paper No.\ 33, 1096--1120. 2015.
** F.\ Gadducci, R.\  Heckel. An inductive view of graph transformation. \emph{Recent trends in algebraic development techniques}, 223--237, Lecture Notes in Comput. Sci., 1376, Springer, Berlin. 1998.
** S.\ Lack, and P.\ Soboci\'{n}ski. Adhesive categories. In \emph{International Conference on Foundations of Software Science and Computation Structures}, 273--288. Springer, Berlin, Heidelberg. 2004.
** G.\ Wraith. Artin glueing. \emph{J.\ Pure Appl.\ Algebra} \textbf{4}, 345--348. 1974.
